const assert = require('assert');
const universalOrbitMapPart1 = require('../day-06-universal-orbit-map/universal-orbit-map');
const universalOrbitMapPart2 = require('../day-06-universal-orbit-map/universal-orbit-map2');

describe('Day 6: Universal Orbit Map', () => {
    it('should pass test 1', () => {
        const input = 'COM)B\n' +
            'B)C\n' +
            'C)D\n' +
            'D)E\n' +
            'E)F\n' +
            'B)G\n' +
            'G)H\n' +
            'D)I\n' +
            'E)J\n' +
            'J)K\n' +
            'K)L';
        assert.equal(universalOrbitMapPart1(input),42);
    });
    it('should log correct output for Part 1', () => {
        const input = 'FGY)61Z\n' +
            '2BN)LM7\n' +
            'QXY)TVB\n' +
            '5M5)Y6C\n' +
            '2L2)64M\n' +
            '6TT)183\n' +
            'H6P)6TT\n' +
            'LPL)WP5\n' +
            'TDW)SDV\n' +
            '4N3)LHM\n' +
            'MJ7)STL\n' +
            'V17)4QM\n' +
            '2XW)R2P\n' +
            'CMK)P3C\n' +
            'KN5)XBH\n' +
            '4GV)Z17\n' +
            'VQW)KD6\n' +
            'N6Q)GBK\n' +
            'LZC)5R2\n' +
            '3Z1)L7Y\n' +
            '1LV)QCF\n' +
            'NQ5)6K4\n' +
            '3XX)D1H\n' +
            'YT6)DXZ\n' +
            'JFB)CMF\n' +
            'NFC)DYG\n' +
            'VG6)W38\n' +
            '31Z)TCV\n' +
            '597)H8Q\n' +
            'GK1)MSN\n' +
            '69N)W4Y\n' +
            '3NY)1FX\n' +
            'W81)3XX\n' +
            'LP1)KBR\n' +
            '3KD)X65\n' +
            'YSD)HLF\n' +
            'WKN)NXN\n' +
            'C9S)NYS\n' +
            '9DX)Y3V\n' +
            'VY4)YSL\n' +
            '2V4)79M\n' +
            'X68)1RB\n' +
            '53T)H97\n' +
            'TKM)2J1\n' +
            'K8M)N95\n' +
            'HZ2)J3B\n' +
            'R6Z)KQ1\n' +
            '96F)5WS\n' +
            'W68)KQ5\n' +
            'H4G)NCN\n' +
            'WXV)BH6\n' +
            '8Z1)KVB\n' +
            'WGQ)18Y\n' +
            '4M1)9D8\n' +
            '2NH)RLJ\n' +
            'KVB)1Y5\n' +
            '3SG)RFG\n' +
            'GBD)HZJ\n' +
            '1W4)JZ4\n' +
            '4W5)R1J\n' +
            '6KP)GJB\n' +
            '1QS)4D5\n' +
            '1Q4)FDD\n' +
            'DZX)Q8F\n' +
            '7MB)1RF\n' +
            'RFG)TKV\n' +
            'LK4)QTF\n' +
            'YKS)LLV\n' +
            '4Z9)2BL\n' +
            'VNR)WJ4\n' +
            '81Z)KNH\n' +
            '2V7)9LV\n' +
            'MCW)LRD\n' +
            'SGB)HTX\n' +
            'NKK)DGX\n' +
            'MHG)C7W\n' +
            '2T7)6VV\n' +
            'X9J)2CL\n' +
            '8CF)RPP\n' +
            'LVZ)GY6\n' +
            'NDK)D1V\n' +
            'JYG)LTF\n' +
            'ZL3)JP5\n' +
            'RZP)NGS\n' +
            '6LW)212\n' +
            '4QM)6B2\n' +
            '351)ZCK\n' +
            '8FJ)JF9\n' +
            'TH4)XZV\n' +
            '3HK)1W4\n' +
            'DCX)TKM\n' +
            '8JW)CCB\n' +
            'Z5Y)4N7\n' +
            'L73)1XV\n' +
            '4QJ)6VW\n' +
            'F4H)8C7\n' +
            'RKS)BQ9\n' +
            'HHB)RWF\n' +
            '2T7)X5H\n' +
            'XQF)HXM\n' +
            'QKM)CMJ\n' +
            'GC3)RZR\n' +
            'BBL)D5Q\n' +
            'LC7)JBF\n' +
            '8RJ)MZ1\n' +
            'PD9)TYR\n' +
            'MWX)B17\n' +
            'DR1)L88\n' +
            'KBR)B16\n' +
            'CM2)Q2J\n' +
            'J5Q)3WP\n' +
            '3Z1)2XW\n' +
            'YCF)VY4\n' +
            '76M)2V4\n' +
            'CCM)L2Z\n' +
            '7XM)YNQ\n' +
            '7HW)GTK\n' +
            'ZSM)6LC\n' +
            'H9P)G1N\n' +
            '4ZD)B3C\n' +
            'DXZ)39Y\n' +
            '18Y)V17\n' +
            '747)QXY\n' +
            'W26)ZTN\n' +
            'RLJ)J5Q\n' +
            'PHC)96F\n' +
            'ZQD)PMY\n' +
            'BWK)8RJ\n' +
            '8C4)DRX\n' +
            'YL1)NDK\n' +
            'W19)PFH\n' +
            'T6V)X8G\n' +
            'LPR)TRR\n' +
            'JRV)NF8\n' +
            '248)XVV\n' +
            'KQ1)H3P\n' +
            '747)BSB\n' +
            '8PH)C4N\n' +
            '7ZT)9M8\n' +
            'FPQ)QKH\n' +
            'LXZ)CYZ\n' +
            'VZX)681\n' +
            'PRZ)6J4\n' +
            'XZ6)91R\n' +
            'G77)QG1\n' +
            'QCF)G3S\n' +
            'NXN)XT1\n' +
            'K95)DY2\n' +
            '1JF)NNH\n' +
            '4N7)7W3\n' +
            '5RQ)PBN\n' +
            'JRS)8D1\n' +
            'G7C)8SK\n' +
            'H3P)H16\n' +
            '346)Q8Q\n' +
            'HH7)5LZ\n' +
            'HZJ)WFK\n' +
            'FRH)81J\n' +
            'DQM)K3X\n' +
            'HTX)9RN\n' +
            'VV9)4Z9\n' +
            'X6T)T37\n' +
            'JC7)K7H\n' +
            'P98)9SF\n' +
            '9SD)XFM\n' +
            'V9P)B98\n' +
            'BG7)8NQ\n' +
            'YPZ)PMJ\n' +
            '5VN)NFR\n' +
            'T9Z)LK4\n' +
            'J5G)N4K\n' +
            'X5R)GFG\n' +
            'TZP)MK5\n' +
            '2B4)5MV\n' +
            'FNG)RTR\n' +
            'WFK)HXC\n' +
            'BJ7)R2J\n' +
            'HCZ)HVV\n' +
            '1CM)HYW\n' +
            '9FL)DPR\n' +
            'JPQ)FFS\n' +
            'P5P)6VT\n' +
            'D1V)MJK\n' +
            'RZB)Q92\n' +
            'M72)QP1\n' +
            '8ZZ)L16\n' +
            '7FB)XZN\n' +
            'X6C)TSV\n' +
            'MK5)SC7\n' +
            '9B4)7ZX\n' +
            'JZ4)6C5\n' +
            '5H2)33S\n' +
            'WY2)487\n' +
            'PFH)1J9\n' +
            '6RF)G42\n' +
            'VH4)T75\n' +
            'JF9)9H3\n' +
            'HL8)DMB\n' +
            'WSR)98S\n' +
            'W6W)NNX\n' +
            'Y6C)LC7\n' +
            'G9P)VLT\n' +
            '6B2)D5V\n' +
            'HXC)GX8\n' +
            'T3V)4B7\n' +
            '9KC)46N\n' +
            'SDV)5T7\n' +
            '8D1)8QG\n' +
            'TZJ)5QJ\n' +
            'MBT)TBD\n' +
            'F1D)M29\n' +
            '19K)C7H\n' +
            'TBN)6KQ\n' +
            'TKC)76M\n' +
            '38H)6L2\n' +
            'ZBK)PVD\n' +
            'DXR)CTS\n' +
            'KCS)XDX\n' +
            'QWW)849\n' +
            '7W3)NMG\n' +
            'BX6)397\n' +
            'Q61)38H\n' +
            'C7H)JFB\n' +
            'K1Y)2ZR\n' +
            '39Y)CMK\n' +
            '3FL)QTP\n' +
            'S7Y)6DR\n' +
            '2YN)J4C\n' +
            'Q8F)PG7\n' +
            'J5W)72Z\n' +
            'CN9)L7M\n' +
            'R1J)53D\n' +
            'YFG)CRC\n' +
            '779)4RY\n' +
            'DGZ)M17\n' +
            '5LZ)BZ3\n' +
            'B5S)FX6\n' +
            '5VV)5P5\n' +
            '8M9)2P8\n' +
            'GT6)J29\n' +
            'WFK)759\n' +
            '8NV)FSB\n' +
            'YWS)Q8X\n' +
            'ZV4)ZLV\n' +
            '6C5)NF5\n' +
            'CP9)XC7\n' +
            '61Z)YH9\n' +
            'VZ8)W81\n' +
            'FGN)JMN\n' +
            'ZSW)72R\n' +
            'JSN)P6K\n' +
            'Y3Z)Q7M\n' +
            'LT7)ZZM\n' +
            '1WZ)319\n' +
            'CGG)D7H\n' +
            'NT4)HG8\n' +
            'RLB)QQR\n' +
            'S4B)3SG\n' +
            'H3Z)BDJ\n' +
            'RZR)GH3\n' +
            'QP1)PND\n' +
            'FSB)PK7\n' +
            'B3C)KGS\n' +
            '4P5)W26\n' +
            'TSV)1LV\n' +
            '37K)1Q4\n' +
            'L5B)J9C\n' +
            'P6K)G14\n' +
            'XZN)CGQ\n' +
            'N95)6LW\n' +
            'W8S)2NH\n' +
            'HXM)GX7\n' +
            '6KQ)ZQY\n' +
            'Y2L)C57\n' +
            'DPR)318\n' +
            '7S8)Y82\n' +
            'Q8J)YJQ\n' +
            '2YC)SX6\n' +
            'DK2)N41\n' +
            'C1N)PRZ\n' +
            'LW3)1P2\n' +
            'GGX)4R2\n' +
            '9FZ)8PH\n' +
            '4WD)3J1\n' +
            'J9C)G9P\n' +
            'J81)XJS\n' +
            'WCJ)2B4\n' +
            'M3V)1QC\n' +
            'QQP)1F7\n' +
            '9HM)979\n' +
            'NGS)72D\n' +
            'CMF)D5N\n' +
            'M2S)VDJ\n' +
            'QW7)LQ8\n' +
            'PFF)4LD\n' +
            '1YN)MHG\n' +
            'FR3)W19\n' +
            'CKS)ST1\n' +
            '1S4)VZX\n' +
            '7S8)M83\n' +
            'L16)7VX\n' +
            'CTS)YFG\n' +
            'WJ4)SGB\n' +
            '4S5)6V7\n' +
            'MF4)7GN\n' +
            'QTP)M5Q\n' +
            '6TD)HXG\n' +
            'QXY)MFG\n' +
            '6K5)JRS\n' +
            'XN6)113\n' +
            'TPY)2YC\n' +
            'XL2)PMC\n' +
            'VSK)THY\n' +
            'L88)8CF\n' +
            'NFR)PCV\n' +
            'MDX)LPZ\n' +
            'D3K)4FG\n' +
            '8YP)L2L\n' +
            'PMY)QJM\n' +
            'GH3)TG5\n' +
            '6KZ)F1H\n' +
            'Y85)X68\n' +
            'CMJ)VMQ\n' +
            'GFG)8Z8\n' +
            '1L1)VH4\n' +
            'BTN)Q91\n' +
            'T7W)TVF\n' +
            '6LC)LPL\n' +
            'BW5)RXF\n' +
            '6VW)X6C\n' +
            '5P5)BK8\n' +
            '24B)VV9\n' +
            'HCT)9KC\n' +
            'Q2J)96V\n' +
            '5D3)97R\n' +
            'BJL)PFS\n' +
            'RTR)J8P\n' +
            'VCJ)8GM\n' +
            '6KF)LNJ\n' +
            'KLB)31Z\n' +
            'VQW)2V7\n' +
            '8CJ)5QS\n' +
            'V2S)QWW\n' +
            '6DR)3KD\n' +
            'D5N)5B5\n' +
            'DK1)Z16\n' +
            'YVB)P7K\n' +
            'WSY)X5R\n' +
            'P13)T4G\n' +
            'VGZ)SYR\n' +
            'LVB)ZWS\n' +
            'RPG)CQP\n' +
            '81J)573\n' +
            'F9B)CKC\n' +
            'M3R)8JW\n' +
            'HL8)G1B\n' +
            'WDN)WYX\n' +
            'ZZ3)F17\n' +
            '7XM)MK1\n' +
            'HKF)VNR\n' +
            'BSB)H4G\n' +
            'JS4)MS6\n' +
            'SXQ)G7N\n' +
            'G1F)5VN\n' +
            'NH5)V2Y\n' +
            '2WF)LS2\n' +
            'K51)SVQ\n' +
            'MM2)MDX\n' +
            'JSN)LR3\n' +
            'FTV)28F\n' +
            'R66)8DH\n' +
            '5JM)Y2L\n' +
            'Q92)GRR\n' +
            '55L)3Z1\n' +
            '2BG)VLB\n' +
            '7GN)P6R\n' +
            '8K3)YCL\n' +
            'KDN)R6Z\n' +
            'GX8)KCS\n' +
            'TCV)H9P\n' +
            '6J4)JS4\n' +
            'Q7M)JRV\n' +
            'NXF)5B3\n' +
            '573)HZC\n' +
            'HZC)F4H\n' +
            'MSN)W3D\n' +
            'TBD)2YQ\n' +
            'YQN)12D\n' +
            'RQX)94S\n' +
            'GTK)RYG\n' +
            'GVG)9WV\n' +
            'CM5)V9P\n' +
            'QP9)JNR\n' +
            'JYG)NN1\n' +
            '2P8)9BZ\n' +
            'FF6)PSW\n' +
            'WB6)NKK\n' +
            'CZJ)H7C\n' +
            'YYH)62H\n' +
            'YSL)LP1\n' +
            'SJJ)YC6\n' +
            '9GB)GSF\n' +
            'P6X)8Z1\n' +
            'P8C)CTR\n' +
            '979)83S\n' +
            'NF5)TBK\n' +
            'TQP)8NV\n' +
            'PC3)YMB\n' +
            'QST)M2S\n' +
            'X56)19Y\n' +
            'Y7G)H3Z\n' +
            '2RN)BDK\n' +
            'TYR)JXJ\n' +
            'NF2)WB6\n' +
            'P7K)DXN\n' +
            'RKH)WZ7\n' +
            '17T)XNK\n' +
            'NL1)QHY\n' +
            'Y82)WJS\n' +
            'L7M)BC5\n' +
            'KJB)ZSW\n' +
            'DXN)KVH\n' +
            'VLW)JPQ\n' +
            'S2D)DGZ\n' +
            'FX6)NYD\n' +
            'FWT)TKC\n' +
            '2JN)VQW\n' +
            'V2Y)X86\n' +
            'H97)XL2\n' +
            'BLC)DCK\n' +
            '6N7)868\n' +
            'FPF)F3R\n' +
            'F1H)WHH\n' +
            'XFM)R2N\n' +
            'PNH)KYQ\n' +
            'J4C)6VX\n' +
            'TVB)G1F\n' +
            'NNX)B66\n' +
            'BZ3)V9W\n' +
            'GMR)QST\n' +
            'RBB)Y34\n' +
            '577)755\n' +
            'SX6)3V2\n' +
            '1L1)DK1\n' +
            'X5V)RZ8\n' +
            'M3F)QF7\n' +
            '8YR)677\n' +
            'M83)FPF\n' +
            'J28)M8L\n' +
            'M83)FRY\n' +
            'T8Y)X6T\n' +
            'MMJ)YL1\n' +
            '487)T2N\n' +
            'TRR)KJB\n' +
            'FFS)QNC\n' +
            'WP5)3L6\n' +
            '6V7)1Z7\n' +
            '9FL)X5Q\n' +
            'W38)2RS\n' +
            '1J9)X92\n' +
            'N9X)9KT\n' +
            '12D)F9B\n' +
            '6QR)DCX\n' +
            '7ZT)MM2\n' +
            'P8K)K51\n' +
            'WKR)M3F\n' +
            'CCB)B29\n' +
            'RSN)VCJ\n' +
            'L7S)37K\n' +
            '5QS)HQR\n' +
            '6RF)NPC\n' +
            'Y1T)2T7\n' +
            'FGB)YT6\n' +
            'MGY)K95\n' +
            'DGX)LWC\n' +
            'TH4)X26\n' +
            'MFG)FPQ\n' +
            'Y7Y)L67\n' +
            'DM6)9NJ\n' +
            'THY)2JN\n' +
            'SMJ)PC3\n' +
            'SZC)S7Y\n' +
            'JPQ)VHY\n' +
            'SKG)11M\n' +
            'YNJ)3HK\n' +
            '2V4)VX3\n' +
            'QP9)711\n' +
            '681)BBL\n' +
            '2G8)8K1\n' +
            'QW9)7HW\n' +
            '9J6)MYL\n' +
            '93R)6TD\n' +
            'J9W)2YN\n' +
            'CRC)VBT\n' +
            'XDD)G9R\n' +
            '97R)9HM\n' +
            'ZCK)TZJ\n' +
            '5WS)9L3\n' +
            'BCW)7PY\n' +
            'XLV)47R\n' +
            'CK9)1L1\n' +
            'GHN)5DM\n' +
            '759)MMJ\n' +
            'WYX)RSC\n' +
            'VLT)1WZ\n' +
            '7T6)PRP\n' +
            '62G)PHC\n' +
            'XBH)4WD\n' +
            '4FG)LVB\n' +
            '1X7)CP9\n' +
            'X5R)8C4\n' +
            'GK1)DQM\n' +
            '3WP)YKS\n' +
            'G42)672\n' +
            'BDJ)7XM\n' +
            '9BZ)W4G\n' +
            'PJJ)YZ4\n' +
            'SQZ)5VV\n' +
            'VK9)45G\n' +
            'R2P)MWX\n' +
            'NHX)YYH\n' +
            '9RW)JC7\n' +
            '94S)VX4\n' +
            'G3Q)R21\n' +
            '6K4)6N7\n' +
            '3L6)4W3\n' +
            '3C3)Y7Y\n' +
            '9M8)NQ5\n' +
            'SJM)68L\n' +
            'P6K)G72\n' +
            'K3X)CZJ\n' +
            'CY6)L5B\n' +
            'LWK)MZG\n' +
            '43Y)QKM\n' +
            '6DR)HH7\n' +
            'HT1)54V\n' +
            '2BL)PX9\n' +
            '5B3)LVZ\n' +
            'Z6H)JYB\n' +
            '5MG)Y8Q\n' +
            'VKJ)VK5\n' +
            'LR3)P6X\n' +
            'F1F)7YW\n' +
            'VY4)W52\n' +
            'VG6)YLW\n' +
            'T1Q)LWG\n' +
            'KYQ)BY7\n' +
            '672)WDN\n' +
            'SR5)SQZ\n' +
            'NKK)DK2\n' +
            'YJQ)XN6\n' +
            '6XD)Y1S\n' +
            'Z5M)QHT\n' +
            'Z6S)BJK\n' +
            'COM)ML7\n' +
            'WB1)DFR\n' +
            'X5H)2L2\n' +
            'C7Q)MJC\n' +
            'BJK)SKV\n' +
            'LC7)7SS\n' +
            'V9W)VZ8\n' +
            'PHF)1YT\n' +
            'G72)QW7\n' +
            'ZJV)346\n' +
            'W3D)8S7\n' +
            'R2N)8CJ\n' +
            'TDL)W6W\n' +
            'DLT)6QR\n' +
            'X92)1M4\n' +
            'WC6)LXZ\n' +
            'BXW)1YY\n' +
            'CN9)VFJ\n' +
            '6KQ)YOU\n' +
            'XNK)NHX\n' +
            'DQ4)X34\n' +
            'MJK)Y55\n' +
            'T75)5YF\n' +
            'PCV)N9X\n' +
            'JBF)SZC\n' +
            'ZLV)VS8\n' +
            '2YC)DLT\n' +
            'RFL)KPR\n' +
            '8N7)FDY\n' +
            'PND)GMR\n' +
            'DRX)69N\n' +
            '45G)P3N\n' +
            'NYS)9B4\n' +
            'YDY)NWQ\n' +
            '6GC)DZX\n' +
            'NMG)TJ2\n' +
            'PFS)JYG\n' +
            'KNT)5FZ\n' +
            'ZYN)ZQ2\n' +
            'K9P)RQX\n' +
            'ML8)B9J\n' +
            'PRP)9GB\n' +
            '67N)JSN\n' +
            '3HG)GHN\n' +
            'PYN)KJN\n' +
            'GVG)WY9\n' +
            'S8N)YT5\n' +
            'VFJ)2RN\n' +
            '6VX)6LB\n' +
            'FHY)7DC\n' +
            'D65)4N3\n' +
            'BH6)MF4\n' +
            'DKW)M3J\n' +
            'DYG)3FP\n' +
            'YC8)HZ2\n' +
            'G8R)M3R\n' +
            'HXG)HWS\n' +
            'CQP)LW3\n' +
            'GCH)9SD\n' +
            '4HR)LX9\n' +
            'KQ5)YV4\n' +
            '2V2)C9S\n' +
            '3J1)TP4\n' +
            'XPL)QVR\n' +
            'TG5)GQB\n' +
            'KVH)VQ7\n' +
            'JMN)BX6\n' +
            'QX9)72M\n' +
            '4RY)Z6H\n' +
            'HGN)SAN\n' +
            'NF8)577\n' +
            '72D)BLC\n' +
            'QG1)125\n' +
            'SYR)XZ3\n' +
            'WW5)LZC\n' +
            '5YF)X56\n' +
            'N9R)ZZ3\n' +
            '6VT)YPR\n' +
            '8S7)XDD\n' +
            '65Y)P5P\n' +
            '9SF)R6Y\n' +
            'GJB)LWK\n' +
            '9RN)QYV\n' +
            'THY)Y85\n' +
            '1YT)1JF\n' +
            'TKC)ZQD\n' +
            'PD9)YNJ\n' +
            '3FP)DKW\n' +
            'XDX)D91\n' +
            'G9R)BCV\n' +
            'RXF)BXW\n' +
            '44W)FGB\n' +
            'GY6)1ZW\n' +
            'TTT)PZ7\n' +
            'LTF)4GZ\n' +
            '9NJ)RMB\n' +
            'CYJ)7XL\n' +
            '183)PQF\n' +
            '319)WC6\n' +
            'DY9)8ZZ\n' +
            'P7W)VSK\n' +
            'G1F)F4Y\n' +
            'MZ1)1YN\n' +
            'JRF)M9R\n' +
            '3V2)QXF\n' +
            'STL)C7Q\n' +
            '6VV)CN9\n' +
            'QF7)G93\n' +
            'PSW)FRD\n' +
            'T2N)8N7\n' +
            'Z17)4ZD\n' +
            'P5X)M8C\n' +
            'GX7)YLK\n' +
            'PMJ)N2Y\n' +
            'HG8)W8S\n' +
            'WH4)ZBK\n' +
            '6RT)FGN\n' +
            '9WV)K1T\n' +
            'B98)YVB\n' +
            'H7C)WXV\n' +
            'YH9)MGY\n' +
            'NNH)65Y\n' +
            'VQ7)3NY\n' +
            'RGV)V9J\n' +
            'B2H)NF2\n' +
            'HQR)L4D\n' +
            'LM7)S4B\n' +
            'JBS)GK1\n' +
            'DRX)YDY\n' +
            'JNR)8YP\n' +
            '1F7)DXR\n' +
            'FRD)ML8\n' +
            'RQ6)9SW\n' +
            'TP4)BW5\n' +
            'MYL)HL8\n' +
            'VS8)J81\n' +
            'Y9Z)CNZ\n' +
            'Y1S)DC6\n' +
            '4GZ)N9R\n' +
            'M5M)MJ7\n' +
            '2BN)DR1\n' +
            '53D)G7C\n' +
            'G14)QX9\n' +
            'Y9L)2P6\n' +
            'XSQ)GYL\n' +
            'MJD)Y9L\n' +
            'P3C)2P7\n' +
            'Q3P)MSM\n' +
            'QVR)WB1\n' +
            'X9R)RKS\n' +
            'CGG)38V\n' +
            '5VN)QQP\n' +
            '96V)F1D\n' +
            'ZQY)Y8L\n' +
            'M29)P8K\n' +
            'CKC)JC3\n' +
            'TDW)VW5\n' +
            'Q91)FNR\n' +
            'X5Q)YCT\n' +
            'PZ7)4FZ\n' +
            'ZL3)114\n' +
            'K1T)J6S\n' +
            'B17)779\n' +
            'PQF)NXF\n' +
            'NCN)3FL\n' +
            'W4G)NTH\n' +
            '7PY)74M\n' +
            'VDJ)JW4\n' +
            'V1F)GDQ\n' +
            'QQR)YQN\n' +
            '2S5)RBB\n' +
            '7FF)597\n' +
            'MS6)V4N\n' +
            'QW9)4P5\n' +
            'BLC)C31\n' +
            'QTF)ZVX\n' +
            'YNJ)RHQ\n' +
            'G93)6KZ\n' +
            'P3N)P8C\n' +
            'G9P)ZSM\n' +
            '91R)LPG\n' +
            'PG7)VRY\n' +
            'DCK)D65\n' +
            'CCB)BTN\n' +
            'D7H)D3K\n' +
            'XT1)W5Q\n' +
            '7DC)M72\n' +
            'PK7)H6P\n' +
            '6VW)1FS\n' +
            'KGS)HHN\n' +
            'WZ7)J4Q\n' +
            'RSW)RQ6\n' +
            'M4B)7T6\n' +
            'LLV)YSD\n' +
            'WDN)7FF\n' +
            'DTY)WGQ\n' +
            'P5P)3HG\n' +
            'H6P)5RQ\n' +
            '64M)4TV\n' +
            '8GM)LCC\n' +
            '1YY)G8R\n' +
            'XVV)DM6\n' +
            'WY9)XKN\n' +
            'QHY)G43\n' +
            '7SS)T6V\n' +
            'PX9)SR5\n' +
            'VK5)81Z\n' +
            'YG3)V1F\n' +
            'YT5)CKS\n' +
            'F17)SH3\n' +
            '2JP)2G8\n' +
            '6LC)RZB\n' +
            'XS1)RGV\n' +
            'R2J)2V2\n' +
            'QKH)L5N\n' +
            'ZZB)YG3\n' +
            'Y8L)6C2\n' +
            'YPR)3ZK\n' +
            '7YW)1RM\n' +
            '9DP)9DX\n' +
            'V9P)248\n' +
            'N2Y)D8V\n' +
            'TVB)KLB\n' +
            '5YF)RFL\n' +
            'SM3)595\n' +
            'DXR)8FJ\n' +
            'PBN)G77\n' +
            'QDC)MBT\n' +
            '595)PNH\n' +
            '5B5)DTY\n' +
            'CNZ)L7X\n' +
            'VW5)CK9\n' +
            'HLF)K7N\n' +
            'VRY)PGG\n' +
            'GRR)C1N\n' +
            'L4D)PQ7\n' +
            'YLW)1QS\n' +
            'YLK)X5V\n' +
            'H8Q)Z1Q\n' +
            'FRY)VLW\n' +
            'LWC)ZJV\n' +
            'KGL)DP8\n' +
            'XC7)48H\n' +
            'ML7)V6Q\n' +
            'YLW)Q3P\n' +
            'CGQ)PFF\n' +
            'X5Q)61X\n' +
            '46N)S2D\n' +
            'QHT)8K3\n' +
            'JNY)F9R\n' +
            '2LS)QS5\n' +
            'XZV)4S5\n' +
            'CYZ)KN5\n' +
            'NYD)T3V\n' +
            '1FX)Z6S\n' +
            '2WD)VKJ\n' +
            '9H3)PYN\n' +
            'JC3)VR5\n' +
            'DXZ)FNG\n' +
            'D1H)TTT\n' +
            'XJM)PHF\n' +
            'B16)WSR\n' +
            'HYW)24B\n' +
            'RRM)L3N\n' +
            '1P2)1S4\n' +
            '7ZX)2BN\n' +
            '8DH)JRF\n' +
            'SC7)DY9\n' +
            'L2L)9FZ\n' +
            '1FS)DQ4\n' +
            'VK9)ZZB\n' +
            'TKV)BPX\n' +
            'F1D)J71\n' +
            '83S)TH4\n' +
            'J3B)VGZ\n' +
            '771)WY2\n' +
            '5PJ)W68\n' +
            '1RB)YPZ\n' +
            'YT5)CGG\n' +
            'HWS)P13\n' +
            '9J6)CY6\n' +
            'LRD)JNY\n' +
            'LPD)5MG\n' +
            '1M4)SJM\n' +
            'FLZ)TZP\n' +
            'LPG)XPL\n' +
            'Z1Q)QCV\n' +
            'B2B)TDW\n' +
            'F3R)GC3\n' +
            'DMB)FTV\n' +
            '1RF)V2S\n' +
            'YC8)XS1\n' +
            '1X4)QP9\n' +
            'NN1)1X7\n' +
            '9VC)LFC\n' +
            'GSF)PD9\n' +
            'KD8)RKH\n' +
            'JW4)2WD\n' +
            '53D)MCW\n' +
            'RWF)HGN\n' +
            'QCV)2JP\n' +
            'G3S)HCZ\n' +
            '4LD)4GV\n' +
            '2RS)T8Y\n' +
            '6JT)BR1\n' +
            '7XL)GCH\n' +
            'FNR)WS8\n' +
            'HSV)LPD\n' +
            'GRT)S8N\n' +
            'V6Q)TPY\n' +
            'RHS)GBD\n' +
            'MK1)T7W\n' +
            'GDQ)BCW\n' +
            'J71)B2H\n' +
            'FTV)67N\n' +
            '8NM)D43\n' +
            'Y8Q)H2X\n' +
            'SVQ)MJD\n' +
            '8QG)55L\n' +
            '5FZ)M5M\n' +
            'VX4)9FL\n' +
            'M5Q)4M1\n' +
            'SM3)ZL3\n' +
            'Z16)FF6\n' +
            'M3J)9DP\n' +
            '125)Q61\n' +
            'FDD)6KP\n' +
            'CMF)1G1\n' +
            'BZD)XQF\n' +
            'RSC)6DT\n' +
            'X8G)YLS\n' +
            'X26)KNT\n' +
            'P98)Y3Z\n' +
            'F5V)4QJ\n' +
            '4B7)NFC\n' +
            '5T7)Z5Y\n' +
            'BDK)3C3\n' +
            'J29)K9P\n' +
            '114)9VC\n' +
            '5MV)J5W\n' +
            'C2Q)LDB\n' +
            'D5V)CJ1\n' +
            '8Z8)SXQ\n' +
            'Y55)X9J\n' +
            'XZ3)X5T\n' +
            'R6Y)XJM\n' +
            'G43)17T\n' +
            'JXJ)7S8\n' +
            '6LB)T9Z\n' +
            'BPX)TBN\n' +
            'RYG)X9R\n' +
            'YC6)6K5\n' +
            '212)6GC\n' +
            '19R)62G\n' +
            '1Z7)HT1\n' +
            'X68)ZV4\n' +
            'RZ8)FGY\n' +
            '72R)Y1T\n' +
            'MJC)52Z\n' +
            '1G1)TDL\n' +
            'T75)SJJ\n' +
            'Y3V)L73\n' +
            'J4Q)FR3\n' +
            'LFC)JKP\n' +
            'HHN)WH4\n' +
            '262)J28\n' +
            'QNC)B2B\n' +
            '4W3)GYK\n' +
            'JP5)GVG\n' +
            'DC6)4W5\n' +
            'KNH)NT4\n' +
            'X65)RPG\n' +
            'Q92)5DK\n' +
            'CQP)5PJ\n' +
            'QYM)LDX\n' +
            'DY2)CM5\n' +
            'T7V)7C5\n' +
            'K7N)LPR\n' +
            'M8L)W33\n' +
            '1XV)19K\n' +
            'W4Y)YCF\n' +
            'FDY)GT6\n' +
            'WS8)6KF\n' +
            'BC5)VXF\n' +
            'BY7)8M9\n' +
            '9L3)SM3\n' +
            'JKP)M15\n' +
            'YMB)484\n' +
            'YCL)KGL\n' +
            '3FP)BVD\n' +
            'Y34)VG6\n' +
            'VHY)BG7\n' +
            'BC5)CYJ\n' +
            'ZVX)FHY\n' +
            'W33)7MB\n' +
            'VQ7)747\n' +
            'WSY)5M5\n' +
            '711)QYM\n' +
            '5R2)2LS\n' +
            'X34)WSY\n' +
            'GYL)HMG\n' +
            '318)M4B\n' +
            '5QJ)HHB\n' +
            'B29)8R7\n' +
            'HMG)53T\n' +
            'CTR)771\n' +
            '1N9)HSV\n' +
            '1ZW)WKN\n' +
            'M8C)6XD\n' +
            '61X)JN5\n' +
            'R21)F5V\n' +
            'RPP)7ZT\n' +
            '68L)BJ7\n' +
            'NJB)VK9\n' +
            '8HV)ZBW\n' +
            '49Z)CCM\n' +
            'LHM)RB8\n' +
            'LVZ)P98\n' +
            'QXF)J9W\n' +
            '677)G3Q\n' +
            'V9J)P5X\n' +
            'PZ7)BWK\n' +
            'L5N)K1Y\n' +
            'PVD)6RF\n' +
            'VKX)C2Q\n' +
            '9SD)FRH\n' +
            '8R7)7FB\n' +
            '38V)T1Q\n' +
            '4D5)1N9\n' +
            '9LV)RSN\n' +
            '9WV)HCT\n' +
            'BVD)Z5M\n' +
            '2J1)K8M\n' +
            '19Y)2BG\n' +
            'G7N)RZP\n' +
            'J6S)HKF\n' +
            '1QC)QDC\n' +
            'C57)GRT\n' +
            '397)5H2\n' +
            'F4Y)WKR\n' +
            'LFC)43Y\n' +
            'HCZ)1X4\n' +
            'K7H)5J7\n' +
            'Q8X)SMJ\n' +
            'J8P)J5G\n' +
            '5DK)FLZ\n' +
            'QYV)RLB\n' +
            'M9R)NJB\n' +
            'W52)262\n' +
            'GFH)N6Q\n' +
            'KJN)PJJ\n' +
            'VX3)49Z\n' +
            'LS2)Q4D\n' +
            'NPC)TQP\n' +
            'B2H)HMK\n' +
            '5DM)2WF\n' +
            'TJ2)WKB\n' +
            'NWQ)NN3\n' +
            '62H)5D3\n' +
            'LQ8)5JM\n' +
            'F9R)R66\n' +
            '6L2)WW5\n' +
            'RMB)VKX\n' +
            'VXF)19R\n' +
            'VMQ)WZ1\n' +
            '6C2)Y9Z\n' +
            'YCT)6RT\n' +
            'YNQ)QW9\n' +
            'LWG)4HR\n' +
            '7C5)351\n' +
            'BK8)B5S\n' +
            '79M)2S5\n' +
            'BCV)6TZ\n' +
            'KPR)WCJ\n' +
            '6TZ)Q8J\n' +
            'XLV)1CM\n' +
            '2YQ)W1M\n' +
            'M17)9J6\n' +
            'H4G)M3V\n' +
            '8SK)CM2\n' +
            'V4N)FWT\n' +
            '4TV)93R\n' +
            'ZZM)9RW\n' +
            'VLB)6S1\n' +
            'G1B)KDN\n' +
            '6XD)P7W\n' +
            'GBK)8HV\n' +
            'KGL)44W\n' +
            'ZBW)ZYN\n' +
            '28F)8NM\n' +
            'Q4D)JBS\n' +
            'RB8)GGX\n' +
            'XKN)LT7\n' +
            'Q29)BZD\n' +
            '47R)L7S\n' +
            'JN5)KD8\n' +
            'G7N)YC8\n' +
            'VR5)NH5\n' +
            'JNR)BJL\n' +
            'PQ7)XLV\n' +
            'WJS)6JT\n' +
            'RHQ)XZ6\n' +
            '113)Q29\n' +
            'VCJ)XSQ\n' +
            '52Z)T7V\n' +
            'L7X)SKG\n' +
            'S8N)Y7G\n' +
            'CJ1)NL1\n' +
            'QS5)RRM\n' +
            'C4N)RHS\n' +
            '484)8YR\n' +
            'SKV)YWS\n' +
            '72M)F1F\n' +
            '3ZK)RSW\n' +
            '1LV)GFH';
        console.log('Answer = ', universalOrbitMapPart1(input));
    });
    it('should return correct answer for test 1 Part 2', () => {
       const input = 'COM)B\n' +
           'B)C\n' +
           'C)D\n' +
           'D)E\n' +
           'E)F\n' +
           'B)G\n' +
           'G)H\n' +
           'D)I\n' +
           'E)J\n' +
           'J)K\n' +
           'K)L\n' +
           'K)YOU\n' +
           'I)SAN';

       assert.equal(universalOrbitMapPart2(input), 4);
    });
    it('should print out result for Part 2', () => {
        const input = 'FGY)61Z\n' +
            '2BN)LM7\n' +
            'QXY)TVB\n' +
            '5M5)Y6C\n' +
            '2L2)64M\n' +
            '6TT)183\n' +
            'H6P)6TT\n' +
            'LPL)WP5\n' +
            'TDW)SDV\n' +
            '4N3)LHM\n' +
            'MJ7)STL\n' +
            'V17)4QM\n' +
            '2XW)R2P\n' +
            'CMK)P3C\n' +
            'KN5)XBH\n' +
            '4GV)Z17\n' +
            'VQW)KD6\n' +
            'N6Q)GBK\n' +
            'LZC)5R2\n' +
            '3Z1)L7Y\n' +
            '1LV)QCF\n' +
            'NQ5)6K4\n' +
            '3XX)D1H\n' +
            'YT6)DXZ\n' +
            'JFB)CMF\n' +
            'NFC)DYG\n' +
            'VG6)W38\n' +
            '31Z)TCV\n' +
            '597)H8Q\n' +
            'GK1)MSN\n' +
            '69N)W4Y\n' +
            '3NY)1FX\n' +
            'W81)3XX\n' +
            'LP1)KBR\n' +
            '3KD)X65\n' +
            'YSD)HLF\n' +
            'WKN)NXN\n' +
            'C9S)NYS\n' +
            '9DX)Y3V\n' +
            'VY4)YSL\n' +
            '2V4)79M\n' +
            'X68)1RB\n' +
            '53T)H97\n' +
            'TKM)2J1\n' +
            'K8M)N95\n' +
            'HZ2)J3B\n' +
            'R6Z)KQ1\n' +
            '96F)5WS\n' +
            'W68)KQ5\n' +
            'H4G)NCN\n' +
            'WXV)BH6\n' +
            '8Z1)KVB\n' +
            'WGQ)18Y\n' +
            '4M1)9D8\n' +
            '2NH)RLJ\n' +
            'KVB)1Y5\n' +
            '3SG)RFG\n' +
            'GBD)HZJ\n' +
            '1W4)JZ4\n' +
            '4W5)R1J\n' +
            '6KP)GJB\n' +
            '1QS)4D5\n' +
            '1Q4)FDD\n' +
            'DZX)Q8F\n' +
            '7MB)1RF\n' +
            'RFG)TKV\n' +
            'LK4)QTF\n' +
            'YKS)LLV\n' +
            '4Z9)2BL\n' +
            'VNR)WJ4\n' +
            '81Z)KNH\n' +
            '2V7)9LV\n' +
            'MCW)LRD\n' +
            'SGB)HTX\n' +
            'NKK)DGX\n' +
            'MHG)C7W\n' +
            '2T7)6VV\n' +
            'X9J)2CL\n' +
            '8CF)RPP\n' +
            'LVZ)GY6\n' +
            'NDK)D1V\n' +
            'JYG)LTF\n' +
            'ZL3)JP5\n' +
            'RZP)NGS\n' +
            '6LW)212\n' +
            '4QM)6B2\n' +
            '351)ZCK\n' +
            '8FJ)JF9\n' +
            'TH4)XZV\n' +
            '3HK)1W4\n' +
            'DCX)TKM\n' +
            '8JW)CCB\n' +
            'Z5Y)4N7\n' +
            'L73)1XV\n' +
            '4QJ)6VW\n' +
            'F4H)8C7\n' +
            'RKS)BQ9\n' +
            'HHB)RWF\n' +
            '2T7)X5H\n' +
            'XQF)HXM\n' +
            'QKM)CMJ\n' +
            'GC3)RZR\n' +
            'BBL)D5Q\n' +
            'LC7)JBF\n' +
            '8RJ)MZ1\n' +
            'PD9)TYR\n' +
            'MWX)B17\n' +
            'DR1)L88\n' +
            'KBR)B16\n' +
            'CM2)Q2J\n' +
            'J5Q)3WP\n' +
            '3Z1)2XW\n' +
            'YCF)VY4\n' +
            '76M)2V4\n' +
            'CCM)L2Z\n' +
            '7XM)YNQ\n' +
            '7HW)GTK\n' +
            'ZSM)6LC\n' +
            'H9P)G1N\n' +
            '4ZD)B3C\n' +
            'DXZ)39Y\n' +
            '18Y)V17\n' +
            '747)QXY\n' +
            'W26)ZTN\n' +
            'RLJ)J5Q\n' +
            'PHC)96F\n' +
            'ZQD)PMY\n' +
            'BWK)8RJ\n' +
            '8C4)DRX\n' +
            'YL1)NDK\n' +
            'W19)PFH\n' +
            'T6V)X8G\n' +
            'LPR)TRR\n' +
            'JRV)NF8\n' +
            '248)XVV\n' +
            'KQ1)H3P\n' +
            '747)BSB\n' +
            '8PH)C4N\n' +
            '7ZT)9M8\n' +
            'FPQ)QKH\n' +
            'LXZ)CYZ\n' +
            'VZX)681\n' +
            'PRZ)6J4\n' +
            'XZ6)91R\n' +
            'G77)QG1\n' +
            'QCF)G3S\n' +
            'NXN)XT1\n' +
            'K95)DY2\n' +
            '1JF)NNH\n' +
            '4N7)7W3\n' +
            '5RQ)PBN\n' +
            'JRS)8D1\n' +
            'G7C)8SK\n' +
            'H3P)H16\n' +
            '346)Q8Q\n' +
            'HH7)5LZ\n' +
            'HZJ)WFK\n' +
            'FRH)81J\n' +
            'DQM)K3X\n' +
            'HTX)9RN\n' +
            'VV9)4Z9\n' +
            'X6T)T37\n' +
            'JC7)K7H\n' +
            'P98)9SF\n' +
            '9SD)XFM\n' +
            'V9P)B98\n' +
            'BG7)8NQ\n' +
            'YPZ)PMJ\n' +
            '5VN)NFR\n' +
            'T9Z)LK4\n' +
            'J5G)N4K\n' +
            'X5R)GFG\n' +
            'TZP)MK5\n' +
            '2B4)5MV\n' +
            'FNG)RTR\n' +
            'WFK)HXC\n' +
            'BJ7)R2J\n' +
            'HCZ)HVV\n' +
            '1CM)HYW\n' +
            '9FL)DPR\n' +
            'JPQ)FFS\n' +
            'P5P)6VT\n' +
            'D1V)MJK\n' +
            'RZB)Q92\n' +
            'M72)QP1\n' +
            '8ZZ)L16\n' +
            '7FB)XZN\n' +
            'X6C)TSV\n' +
            'MK5)SC7\n' +
            '9B4)7ZX\n' +
            'JZ4)6C5\n' +
            '5H2)33S\n' +
            'WY2)487\n' +
            'PFH)1J9\n' +
            '6RF)G42\n' +
            'VH4)T75\n' +
            'JF9)9H3\n' +
            'HL8)DMB\n' +
            'WSR)98S\n' +
            'W6W)NNX\n' +
            'Y6C)LC7\n' +
            'G9P)VLT\n' +
            '6B2)D5V\n' +
            'HXC)GX8\n' +
            'T3V)4B7\n' +
            '9KC)46N\n' +
            'SDV)5T7\n' +
            '8D1)8QG\n' +
            'TZJ)5QJ\n' +
            'MBT)TBD\n' +
            'F1D)M29\n' +
            '19K)C7H\n' +
            'TBN)6KQ\n' +
            'TKC)76M\n' +
            '38H)6L2\n' +
            'ZBK)PVD\n' +
            'DXR)CTS\n' +
            'KCS)XDX\n' +
            'QWW)849\n' +
            '7W3)NMG\n' +
            'BX6)397\n' +
            'Q61)38H\n' +
            'C7H)JFB\n' +
            'K1Y)2ZR\n' +
            '39Y)CMK\n' +
            '3FL)QTP\n' +
            'S7Y)6DR\n' +
            '2YN)J4C\n' +
            'Q8F)PG7\n' +
            'J5W)72Z\n' +
            'CN9)L7M\n' +
            'R1J)53D\n' +
            'YFG)CRC\n' +
            '779)4RY\n' +
            'DGZ)M17\n' +
            '5LZ)BZ3\n' +
            'B5S)FX6\n' +
            '5VV)5P5\n' +
            '8M9)2P8\n' +
            'GT6)J29\n' +
            'WFK)759\n' +
            '8NV)FSB\n' +
            'YWS)Q8X\n' +
            'ZV4)ZLV\n' +
            '6C5)NF5\n' +
            'CP9)XC7\n' +
            '61Z)YH9\n' +
            'VZ8)W81\n' +
            'FGN)JMN\n' +
            'ZSW)72R\n' +
            'JSN)P6K\n' +
            'Y3Z)Q7M\n' +
            'LT7)ZZM\n' +
            '1WZ)319\n' +
            'CGG)D7H\n' +
            'NT4)HG8\n' +
            'RLB)QQR\n' +
            'S4B)3SG\n' +
            'H3Z)BDJ\n' +
            'RZR)GH3\n' +
            'QP1)PND\n' +
            'FSB)PK7\n' +
            'B3C)KGS\n' +
            '4P5)W26\n' +
            'TSV)1LV\n' +
            '37K)1Q4\n' +
            'L5B)J9C\n' +
            'P6K)G14\n' +
            'XZN)CGQ\n' +
            'N95)6LW\n' +
            'W8S)2NH\n' +
            'HXM)GX7\n' +
            '6KQ)ZQY\n' +
            'Y2L)C57\n' +
            'DPR)318\n' +
            '7S8)Y82\n' +
            'Q8J)YJQ\n' +
            '2YC)SX6\n' +
            'DK2)N41\n' +
            'C1N)PRZ\n' +
            'LW3)1P2\n' +
            'GGX)4R2\n' +
            '9FZ)8PH\n' +
            '4WD)3J1\n' +
            'J9C)G9P\n' +
            'J81)XJS\n' +
            'WCJ)2B4\n' +
            'M3V)1QC\n' +
            'QQP)1F7\n' +
            '9HM)979\n' +
            'NGS)72D\n' +
            'CMF)D5N\n' +
            'M2S)VDJ\n' +
            'QW7)LQ8\n' +
            'PFF)4LD\n' +
            '1YN)MHG\n' +
            'FR3)W19\n' +
            'CKS)ST1\n' +
            '1S4)VZX\n' +
            '7S8)M83\n' +
            'L16)7VX\n' +
            'CTS)YFG\n' +
            'WJ4)SGB\n' +
            '4S5)6V7\n' +
            'MF4)7GN\n' +
            'QTP)M5Q\n' +
            '6TD)HXG\n' +
            'QXY)MFG\n' +
            '6K5)JRS\n' +
            'XN6)113\n' +
            'TPY)2YC\n' +
            'XL2)PMC\n' +
            'VSK)THY\n' +
            'L88)8CF\n' +
            'NFR)PCV\n' +
            'MDX)LPZ\n' +
            'D3K)4FG\n' +
            '8YP)L2L\n' +
            'PMY)QJM\n' +
            'GH3)TG5\n' +
            '6KZ)F1H\n' +
            'Y85)X68\n' +
            'CMJ)VMQ\n' +
            'GFG)8Z8\n' +
            '1L1)VH4\n' +
            'BTN)Q91\n' +
            'T7W)TVF\n' +
            '6LC)LPL\n' +
            'BW5)RXF\n' +
            '6VW)X6C\n' +
            '5P5)BK8\n' +
            '24B)VV9\n' +
            'HCT)9KC\n' +
            'Q2J)96V\n' +
            '5D3)97R\n' +
            'BJL)PFS\n' +
            'RTR)J8P\n' +
            'VCJ)8GM\n' +
            '6KF)LNJ\n' +
            'KLB)31Z\n' +
            'VQW)2V7\n' +
            '8CJ)5QS\n' +
            'V2S)QWW\n' +
            '6DR)3KD\n' +
            'D5N)5B5\n' +
            'DK1)Z16\n' +
            'YVB)P7K\n' +
            'WSY)X5R\n' +
            'P13)T4G\n' +
            'VGZ)SYR\n' +
            'LVB)ZWS\n' +
            'RPG)CQP\n' +
            '81J)573\n' +
            'F9B)CKC\n' +
            'M3R)8JW\n' +
            'HL8)G1B\n' +
            'WDN)WYX\n' +
            'ZZ3)F17\n' +
            '7XM)MK1\n' +
            'HKF)VNR\n' +
            'BSB)H4G\n' +
            'JS4)MS6\n' +
            'SXQ)G7N\n' +
            'G1F)5VN\n' +
            'NH5)V2Y\n' +
            '2WF)LS2\n' +
            'K51)SVQ\n' +
            'MM2)MDX\n' +
            'JSN)LR3\n' +
            'FTV)28F\n' +
            'R66)8DH\n' +
            '5JM)Y2L\n' +
            'Q92)GRR\n' +
            '55L)3Z1\n' +
            '2BG)VLB\n' +
            '7GN)P6R\n' +
            '8K3)YCL\n' +
            'KDN)R6Z\n' +
            'GX8)KCS\n' +
            'TCV)H9P\n' +
            '6J4)JS4\n' +
            'Q7M)JRV\n' +
            'NXF)5B3\n' +
            '573)HZC\n' +
            'HZC)F4H\n' +
            'MSN)W3D\n' +
            'TBD)2YQ\n' +
            'YQN)12D\n' +
            'RQX)94S\n' +
            'GTK)RYG\n' +
            'GVG)9WV\n' +
            'CM5)V9P\n' +
            'QP9)JNR\n' +
            'JYG)NN1\n' +
            '2P8)9BZ\n' +
            'FF6)PSW\n' +
            'WB6)NKK\n' +
            'CZJ)H7C\n' +
            'YYH)62H\n' +
            'YSL)LP1\n' +
            'SJJ)YC6\n' +
            '9GB)GSF\n' +
            'P6X)8Z1\n' +
            'P8C)CTR\n' +
            '979)83S\n' +
            'NF5)TBK\n' +
            'TQP)8NV\n' +
            'PC3)YMB\n' +
            'QST)M2S\n' +
            'X56)19Y\n' +
            'Y7G)H3Z\n' +
            '2RN)BDK\n' +
            'TYR)JXJ\n' +
            'NF2)WB6\n' +
            'P7K)DXN\n' +
            'RKH)WZ7\n' +
            '17T)XNK\n' +
            'NL1)QHY\n' +
            'Y82)WJS\n' +
            'L7M)BC5\n' +
            'KJB)ZSW\n' +
            'DXN)KVH\n' +
            'VLW)JPQ\n' +
            'S2D)DGZ\n' +
            'FX6)NYD\n' +
            'FWT)TKC\n' +
            '2JN)VQW\n' +
            'V2Y)X86\n' +
            'H97)XL2\n' +
            'BLC)DCK\n' +
            '6N7)868\n' +
            'FPF)F3R\n' +
            'F1H)WHH\n' +
            'XFM)R2N\n' +
            'PNH)KYQ\n' +
            'J4C)6VX\n' +
            'TVB)G1F\n' +
            'NNX)B66\n' +
            'BZ3)V9W\n' +
            'GMR)QST\n' +
            'RBB)Y34\n' +
            '577)755\n' +
            'SX6)3V2\n' +
            '1L1)DK1\n' +
            'X5V)RZ8\n' +
            'M3F)QF7\n' +
            '8YR)677\n' +
            'M83)FPF\n' +
            'J28)M8L\n' +
            'M83)FRY\n' +
            'T8Y)X6T\n' +
            'MMJ)YL1\n' +
            '487)T2N\n' +
            'TRR)KJB\n' +
            'FFS)QNC\n' +
            'WP5)3L6\n' +
            '6V7)1Z7\n' +
            '9FL)X5Q\n' +
            'W38)2RS\n' +
            '1J9)X92\n' +
            'N9X)9KT\n' +
            '12D)F9B\n' +
            '6QR)DCX\n' +
            '7ZT)MM2\n' +
            'P8K)K51\n' +
            'WKR)M3F\n' +
            'CCB)B29\n' +
            'RSN)VCJ\n' +
            'L7S)37K\n' +
            '5QS)HQR\n' +
            '6RF)NPC\n' +
            'Y1T)2T7\n' +
            'FGB)YT6\n' +
            'MGY)K95\n' +
            'DGX)LWC\n' +
            'TH4)X26\n' +
            'MFG)FPQ\n' +
            'Y7Y)L67\n' +
            'DM6)9NJ\n' +
            'THY)2JN\n' +
            'SMJ)PC3\n' +
            'SZC)S7Y\n' +
            'JPQ)VHY\n' +
            'SKG)11M\n' +
            'YNJ)3HK\n' +
            '2V4)VX3\n' +
            'QP9)711\n' +
            '681)BBL\n' +
            '2G8)8K1\n' +
            'QW9)7HW\n' +
            '9J6)MYL\n' +
            '93R)6TD\n' +
            'J9W)2YN\n' +
            'CRC)VBT\n' +
            'XDD)G9R\n' +
            '97R)9HM\n' +
            'ZCK)TZJ\n' +
            '5WS)9L3\n' +
            'BCW)7PY\n' +
            'XLV)47R\n' +
            'CK9)1L1\n' +
            'GHN)5DM\n' +
            '759)MMJ\n' +
            'WYX)RSC\n' +
            'VLT)1WZ\n' +
            '7T6)PRP\n' +
            '62G)PHC\n' +
            'XBH)4WD\n' +
            '4FG)LVB\n' +
            '1X7)CP9\n' +
            'X5R)8C4\n' +
            'GK1)DQM\n' +
            '3WP)YKS\n' +
            'G42)672\n' +
            'BDJ)7XM\n' +
            '9BZ)W4G\n' +
            'PJJ)YZ4\n' +
            'SQZ)5VV\n' +
            'VK9)45G\n' +
            'R2P)MWX\n' +
            'NHX)YYH\n' +
            '9RW)JC7\n' +
            '94S)VX4\n' +
            'G3Q)R21\n' +
            '6K4)6N7\n' +
            '3L6)4W3\n' +
            '3C3)Y7Y\n' +
            '9M8)NQ5\n' +
            'SJM)68L\n' +
            'P6K)G72\n' +
            'K3X)CZJ\n' +
            'CY6)L5B\n' +
            'LWK)MZG\n' +
            '43Y)QKM\n' +
            '6DR)HH7\n' +
            'HT1)54V\n' +
            '2BL)PX9\n' +
            '5B3)LVZ\n' +
            'Z6H)JYB\n' +
            '5MG)Y8Q\n' +
            'VKJ)VK5\n' +
            'LR3)P6X\n' +
            'F1F)7YW\n' +
            'VY4)W52\n' +
            'VG6)YLW\n' +
            'T1Q)LWG\n' +
            'KYQ)BY7\n' +
            '672)WDN\n' +
            'SR5)SQZ\n' +
            'NKK)DK2\n' +
            'YJQ)XN6\n' +
            '6XD)Y1S\n' +
            'Z5M)QHT\n' +
            'Z6S)BJK\n' +
            'COM)ML7\n' +
            'WB1)DFR\n' +
            'X5H)2L2\n' +
            'C7Q)MJC\n' +
            'BJK)SKV\n' +
            'LC7)7SS\n' +
            'V9W)VZ8\n' +
            'PHF)1YT\n' +
            'G72)QW7\n' +
            'ZJV)346\n' +
            'W3D)8S7\n' +
            'R2N)8CJ\n' +
            'TDL)W6W\n' +
            'DLT)6QR\n' +
            'X92)1M4\n' +
            'WC6)LXZ\n' +
            'BXW)1YY\n' +
            'CN9)VFJ\n' +
            '6KQ)YOU\n' +
            'XNK)NHX\n' +
            'DQ4)X34\n' +
            'MJK)Y55\n' +
            'T75)5YF\n' +
            'PCV)N9X\n' +
            'JBF)SZC\n' +
            'ZLV)VS8\n' +
            '2YC)DLT\n' +
            'RFL)KPR\n' +
            '8N7)FDY\n' +
            'PND)GMR\n' +
            'DRX)69N\n' +
            '45G)P3N\n' +
            'NYS)9B4\n' +
            'YDY)NWQ\n' +
            '6GC)DZX\n' +
            'NMG)TJ2\n' +
            'PFS)JYG\n' +
            'KNT)5FZ\n' +
            'ZYN)ZQ2\n' +
            'K9P)RQX\n' +
            'ML8)B9J\n' +
            'PRP)9GB\n' +
            '67N)JSN\n' +
            '3HG)GHN\n' +
            'PYN)KJN\n' +
            'GVG)WY9\n' +
            'S8N)YT5\n' +
            'VFJ)2RN\n' +
            '6VX)6LB\n' +
            'FHY)7DC\n' +
            'D65)4N3\n' +
            'BH6)MF4\n' +
            'DKW)M3J\n' +
            'DYG)3FP\n' +
            'YC8)HZ2\n' +
            'G8R)M3R\n' +
            'HXG)HWS\n' +
            'CQP)LW3\n' +
            'GCH)9SD\n' +
            '4HR)LX9\n' +
            'KQ5)YV4\n' +
            '2V2)C9S\n' +
            '3J1)TP4\n' +
            'XPL)QVR\n' +
            'TG5)GQB\n' +
            'KVH)VQ7\n' +
            'JMN)BX6\n' +
            'QX9)72M\n' +
            '4RY)Z6H\n' +
            'HGN)SAN\n' +
            'NF8)577\n' +
            '72D)BLC\n' +
            'QG1)125\n' +
            'SYR)XZ3\n' +
            'WW5)LZC\n' +
            '5YF)X56\n' +
            'N9R)ZZ3\n' +
            '6VT)YPR\n' +
            '8S7)XDD\n' +
            '65Y)P5P\n' +
            '9SF)R6Y\n' +
            'GJB)LWK\n' +
            '9RN)QYV\n' +
            'THY)Y85\n' +
            '1YT)1JF\n' +
            'TKC)ZQD\n' +
            'PD9)YNJ\n' +
            '3FP)DKW\n' +
            'XDX)D91\n' +
            'G9R)BCV\n' +
            'RXF)BXW\n' +
            '44W)FGB\n' +
            'GY6)1ZW\n' +
            'TTT)PZ7\n' +
            'LTF)4GZ\n' +
            '9NJ)RMB\n' +
            'CYJ)7XL\n' +
            '183)PQF\n' +
            '319)WC6\n' +
            'DY9)8ZZ\n' +
            'P7W)VSK\n' +
            'G1F)F4Y\n' +
            'MZ1)1YN\n' +
            'JRF)M9R\n' +
            '3V2)QXF\n' +
            'STL)C7Q\n' +
            '6VV)CN9\n' +
            'QF7)G93\n' +
            'PSW)FRD\n' +
            'T2N)8N7\n' +
            'Z17)4ZD\n' +
            'P5X)M8C\n' +
            'GX7)YLK\n' +
            'PMJ)N2Y\n' +
            'HG8)W8S\n' +
            'WH4)ZBK\n' +
            '6RT)FGN\n' +
            '9WV)K1T\n' +
            'B98)YVB\n' +
            'H7C)WXV\n' +
            'YH9)MGY\n' +
            'NNH)65Y\n' +
            'VQ7)3NY\n' +
            'RGV)V9J\n' +
            'B2H)NF2\n' +
            'HQR)L4D\n' +
            'LM7)S4B\n' +
            'JBS)GK1\n' +
            'DRX)YDY\n' +
            'JNR)8YP\n' +
            '1F7)DXR\n' +
            'FRD)ML8\n' +
            'RQ6)9SW\n' +
            'TP4)BW5\n' +
            'MYL)HL8\n' +
            'VS8)J81\n' +
            'Y9Z)CNZ\n' +
            'Y1S)DC6\n' +
            '4GZ)N9R\n' +
            'M5M)MJ7\n' +
            '2BN)DR1\n' +
            '53D)G7C\n' +
            'G14)QX9\n' +
            'Y9L)2P6\n' +
            'XSQ)GYL\n' +
            'MJD)Y9L\n' +
            'P3C)2P7\n' +
            'Q3P)MSM\n' +
            'QVR)WB1\n' +
            'X9R)RKS\n' +
            'CGG)38V\n' +
            '5VN)QQP\n' +
            '96V)F1D\n' +
            'ZQY)Y8L\n' +
            'M29)P8K\n' +
            'CKC)JC3\n' +
            'TDW)VW5\n' +
            'Q91)FNR\n' +
            'X5Q)YCT\n' +
            'PZ7)4FZ\n' +
            'ZL3)114\n' +
            'K1T)J6S\n' +
            'B17)779\n' +
            'PQF)NXF\n' +
            'NCN)3FL\n' +
            'W4G)NTH\n' +
            '7PY)74M\n' +
            'VDJ)JW4\n' +
            'V1F)GDQ\n' +
            'QQR)YQN\n' +
            '2S5)RBB\n' +
            '7FF)597\n' +
            'MS6)V4N\n' +
            'QW9)4P5\n' +
            'BLC)C31\n' +
            'QTF)ZVX\n' +
            'YNJ)RHQ\n' +
            'G93)6KZ\n' +
            'P3N)P8C\n' +
            'G9P)ZSM\n' +
            '91R)LPG\n' +
            'PG7)VRY\n' +
            'DCK)D65\n' +
            'CCB)BTN\n' +
            'D7H)D3K\n' +
            'XT1)W5Q\n' +
            '7DC)M72\n' +
            'PK7)H6P\n' +
            '6VW)1FS\n' +
            'KGS)HHN\n' +
            'WZ7)J4Q\n' +
            'RSW)RQ6\n' +
            'M4B)7T6\n' +
            'LLV)YSD\n' +
            'WDN)7FF\n' +
            'DTY)WGQ\n' +
            'P5P)3HG\n' +
            'H6P)5RQ\n' +
            '64M)4TV\n' +
            '8GM)LCC\n' +
            '1YY)G8R\n' +
            'XVV)DM6\n' +
            'WY9)XKN\n' +
            'QHY)G43\n' +
            '7SS)T6V\n' +
            'PX9)SR5\n' +
            'VK5)81Z\n' +
            'YG3)V1F\n' +
            'YT5)CKS\n' +
            'F17)SH3\n' +
            '2JP)2G8\n' +
            '6LC)RZB\n' +
            'XS1)RGV\n' +
            'R2J)2V2\n' +
            'QKH)L5N\n' +
            'ZZB)YG3\n' +
            'Y8L)6C2\n' +
            'YPR)3ZK\n' +
            '7YW)1RM\n' +
            '9DP)9DX\n' +
            'V9P)248\n' +
            'N2Y)D8V\n' +
            'TVB)KLB\n' +
            '5YF)RFL\n' +
            'SM3)595\n' +
            'DXR)8FJ\n' +
            'PBN)G77\n' +
            'QDC)MBT\n' +
            '595)PNH\n' +
            '5B5)DTY\n' +
            'CNZ)L7X\n' +
            'VW5)CK9\n' +
            'HLF)K7N\n' +
            'VRY)PGG\n' +
            'GRR)C1N\n' +
            'L4D)PQ7\n' +
            'YLW)1QS\n' +
            'YLK)X5V\n' +
            'H8Q)Z1Q\n' +
            'FRY)VLW\n' +
            'LWC)ZJV\n' +
            'KGL)DP8\n' +
            'XC7)48H\n' +
            'ML7)V6Q\n' +
            'YLW)Q3P\n' +
            'CGQ)PFF\n' +
            'X5Q)61X\n' +
            '46N)S2D\n' +
            'QHT)8K3\n' +
            'JNY)F9R\n' +
            '2LS)QS5\n' +
            'XZV)4S5\n' +
            'CYZ)KN5\n' +
            'NYD)T3V\n' +
            '1FX)Z6S\n' +
            '2WD)VKJ\n' +
            '9H3)PYN\n' +
            'JC3)VR5\n' +
            'DXZ)FNG\n' +
            'D1H)TTT\n' +
            'XJM)PHF\n' +
            'B16)WSR\n' +
            'HYW)24B\n' +
            'RRM)L3N\n' +
            '1P2)1S4\n' +
            '7ZX)2BN\n' +
            '8DH)JRF\n' +
            'SC7)DY9\n' +
            'L2L)9FZ\n' +
            '1FS)DQ4\n' +
            'VK9)ZZB\n' +
            'TKV)BPX\n' +
            'F1D)J71\n' +
            '83S)TH4\n' +
            'J3B)VGZ\n' +
            '771)WY2\n' +
            '5PJ)W68\n' +
            '1RB)YPZ\n' +
            'YT5)CGG\n' +
            'HWS)P13\n' +
            '9J6)CY6\n' +
            'LRD)JNY\n' +
            'LPD)5MG\n' +
            '1M4)SJM\n' +
            'FLZ)TZP\n' +
            'LPG)XPL\n' +
            'Z1Q)QCV\n' +
            'B2B)TDW\n' +
            'F3R)GC3\n' +
            'DMB)FTV\n' +
            '1RF)V2S\n' +
            'YC8)XS1\n' +
            '1X4)QP9\n' +
            'NN1)1X7\n' +
            '9VC)LFC\n' +
            'GSF)PD9\n' +
            'KD8)RKH\n' +
            'JW4)2WD\n' +
            '53D)MCW\n' +
            'RWF)HGN\n' +
            'QCV)2JP\n' +
            'G3S)HCZ\n' +
            '4LD)4GV\n' +
            '2RS)T8Y\n' +
            '6JT)BR1\n' +
            '7XL)GCH\n' +
            'FNR)WS8\n' +
            'HSV)LPD\n' +
            'GRT)S8N\n' +
            'V6Q)TPY\n' +
            'RHS)GBD\n' +
            'MK1)T7W\n' +
            'GDQ)BCW\n' +
            'J71)B2H\n' +
            'FTV)67N\n' +
            '8NM)D43\n' +
            'Y8Q)H2X\n' +
            'SVQ)MJD\n' +
            '8QG)55L\n' +
            '5FZ)M5M\n' +
            'VX4)9FL\n' +
            'M5Q)4M1\n' +
            'SM3)ZL3\n' +
            'Z16)FF6\n' +
            'M3J)9DP\n' +
            '125)Q61\n' +
            'FDD)6KP\n' +
            'CMF)1G1\n' +
            'BZD)XQF\n' +
            'RSC)6DT\n' +
            'X8G)YLS\n' +
            'X26)KNT\n' +
            'P98)Y3Z\n' +
            'F5V)4QJ\n' +
            '4B7)NFC\n' +
            '5T7)Z5Y\n' +
            'BDK)3C3\n' +
            'J29)K9P\n' +
            '114)9VC\n' +
            '5MV)J5W\n' +
            'C2Q)LDB\n' +
            'D5V)CJ1\n' +
            '8Z8)SXQ\n' +
            'Y55)X9J\n' +
            'XZ3)X5T\n' +
            'R6Y)XJM\n' +
            'G43)17T\n' +
            'JXJ)7S8\n' +
            '6LB)T9Z\n' +
            'BPX)TBN\n' +
            'RYG)X9R\n' +
            'YC6)6K5\n' +
            '212)6GC\n' +
            '19R)62G\n' +
            '1Z7)HT1\n' +
            'X68)ZV4\n' +
            'RZ8)FGY\n' +
            '72R)Y1T\n' +
            'MJC)52Z\n' +
            '1G1)TDL\n' +
            'T75)SJJ\n' +
            'Y3V)L73\n' +
            'J4Q)FR3\n' +
            'LFC)JKP\n' +
            'HHN)WH4\n' +
            '262)J28\n' +
            'QNC)B2B\n' +
            '4W3)GYK\n' +
            'JP5)GVG\n' +
            'DC6)4W5\n' +
            'KNH)NT4\n' +
            'X65)RPG\n' +
            'Q92)5DK\n' +
            'CQP)5PJ\n' +
            'QYM)LDX\n' +
            'DY2)CM5\n' +
            'T7V)7C5\n' +
            'K7N)LPR\n' +
            'M8L)W33\n' +
            '1XV)19K\n' +
            'W4Y)YCF\n' +
            'FDY)GT6\n' +
            'WS8)6KF\n' +
            'BC5)VXF\n' +
            'BY7)8M9\n' +
            '9L3)SM3\n' +
            'JKP)M15\n' +
            'YMB)484\n' +
            'YCL)KGL\n' +
            '3FP)BVD\n' +
            'Y34)VG6\n' +
            'VHY)BG7\n' +
            'BC5)CYJ\n' +
            'ZVX)FHY\n' +
            'W33)7MB\n' +
            'VQ7)747\n' +
            'WSY)5M5\n' +
            '711)QYM\n' +
            '5R2)2LS\n' +
            'X34)WSY\n' +
            'GYL)HMG\n' +
            '318)M4B\n' +
            '5QJ)HHB\n' +
            'B29)8R7\n' +
            'HMG)53T\n' +
            'CTR)771\n' +
            '1N9)HSV\n' +
            '1ZW)WKN\n' +
            'M8C)6XD\n' +
            '61X)JN5\n' +
            'R21)F5V\n' +
            'RPP)7ZT\n' +
            '68L)BJ7\n' +
            'NJB)VK9\n' +
            '8HV)ZBW\n' +
            '49Z)CCM\n' +
            'LHM)RB8\n' +
            'LVZ)P98\n' +
            'QXF)J9W\n' +
            '677)G3Q\n' +
            'V9J)P5X\n' +
            'PZ7)BWK\n' +
            'L5N)K1Y\n' +
            'PVD)6RF\n' +
            'VKX)C2Q\n' +
            '9SD)FRH\n' +
            '8R7)7FB\n' +
            '38V)T1Q\n' +
            '4D5)1N9\n' +
            '9LV)RSN\n' +
            '9WV)HCT\n' +
            'BVD)Z5M\n' +
            '2J1)K8M\n' +
            '19Y)2BG\n' +
            'G7N)RZP\n' +
            'J6S)HKF\n' +
            '1QC)QDC\n' +
            'C57)GRT\n' +
            '397)5H2\n' +
            'F4Y)WKR\n' +
            'LFC)43Y\n' +
            'HCZ)1X4\n' +
            'K7H)5J7\n' +
            'Q8X)SMJ\n' +
            'J8P)J5G\n' +
            '5DK)FLZ\n' +
            'QYV)RLB\n' +
            'M9R)NJB\n' +
            'W52)262\n' +
            'GFH)N6Q\n' +
            'KJN)PJJ\n' +
            'VX3)49Z\n' +
            'LS2)Q4D\n' +
            'NPC)TQP\n' +
            'B2H)HMK\n' +
            '5DM)2WF\n' +
            'TJ2)WKB\n' +
            'NWQ)NN3\n' +
            '62H)5D3\n' +
            'LQ8)5JM\n' +
            'F9R)R66\n' +
            '6L2)WW5\n' +
            'RMB)VKX\n' +
            'VXF)19R\n' +
            'VMQ)WZ1\n' +
            '6C2)Y9Z\n' +
            'YCT)6RT\n' +
            'YNQ)QW9\n' +
            'LWG)4HR\n' +
            '7C5)351\n' +
            'BK8)B5S\n' +
            '79M)2S5\n' +
            'BCV)6TZ\n' +
            'KPR)WCJ\n' +
            '6TZ)Q8J\n' +
            'XLV)1CM\n' +
            '2YQ)W1M\n' +
            'M17)9J6\n' +
            'H4G)M3V\n' +
            '8SK)CM2\n' +
            'V4N)FWT\n' +
            '4TV)93R\n' +
            'ZZM)9RW\n' +
            'VLB)6S1\n' +
            'G1B)KDN\n' +
            '6XD)P7W\n' +
            'GBK)8HV\n' +
            'KGL)44W\n' +
            'ZBW)ZYN\n' +
            '28F)8NM\n' +
            'Q4D)JBS\n' +
            'RB8)GGX\n' +
            'XKN)LT7\n' +
            'Q29)BZD\n' +
            '47R)L7S\n' +
            'JN5)KD8\n' +
            'G7N)YC8\n' +
            'VR5)NH5\n' +
            'JNR)BJL\n' +
            'PQ7)XLV\n' +
            'WJS)6JT\n' +
            'RHQ)XZ6\n' +
            '113)Q29\n' +
            'VCJ)XSQ\n' +
            '52Z)T7V\n' +
            'L7X)SKG\n' +
            'S8N)Y7G\n' +
            'CJ1)NL1\n' +
            'QS5)RRM\n' +
            'C4N)RHS\n' +
            '484)8YR\n' +
            'SKV)YWS\n' +
            '72M)F1F\n' +
            '3ZK)RSW\n' +
            '1LV)GFH';

        console.log('Answer = ', universalOrbitMapPart2(input));
    });

});
